version: "3.5"
services:
  php-cli:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: $PHP_VERSION
    env_file:
      - .env
    container_name: php-cli
    hostname: zanin-php-cli
    working_dir: /var/www/app
    volumes:
      - ../..:/var/www/app
    networks:
      - mynetwork

networks:
  mynetwork:
    name: mbh-network
    driver: bridge


